--Creacion de sinonimos publicos por tabla 
CREATE PUBLIC SYNONYM PAG FOR ADMIN.PAGOS
CREATE PUBLIC SYNONYM PAC FOR ADMIN.PACIENTE
CREATE PUBLIC SYNONYM BONOS FOR ADMIN.BONO_CONSULTA
CREATE PUBLIC SYNONYM SAL FOR ADMIN.SALUD;

-- Comprobación de sinonimos
SELECT * FROM PAG;
SELECT * FROM PAC;
SELECT * FROM BONOS;
SELECT * FROM SAL;


